// Copyright (c) 2024 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { Main } from '@daml.js/canton-supply-chain-0.1.0';

// In a real project, these types would be imported from the code generated by `dpm codegen-js`.
// For this example, we define them manually to match the expected Daml templates.
export type Asset = Main.Asset.Asset;
export type CustodyTransfer = Main.Custody.CustodyTransfer;
export type Checkpoint = Main.Checkpoint.Checkpoint;

/**
 * Represents a contract on the ledger, including its ID and payload.
 */
export interface LedgerContract<T> {
  contractId: string;
  templateId: string;
  payload: T;
}

/**
 * A unified type representing an event in an asset's history.
 * It can be either a custody transfer or a checkpoint scan.
 */
export type TimelineEvent =
  | { type: 'creation'; timestamp: string; event: Asset }
  | { type: 'transfer'; timestamp: string; event: CustodyTransfer }
  | { type: 'checkpoint'; timestamp: string; event: Checkpoint };


/**
 * Represents the full state and history of a single asset.
 */
export interface AssetProvenance {
  currentAsset: LedgerContract<Asset>;
  timeline: TimelineEvent[];
}

/**
 * A custom error class for ledger service failures.
 */
export class LedgerServiceError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'LedgerServiceError';
  }
}

const JSON_API_URL = import.meta.env.VITE_JSON_API_URL || 'http://localhost:7575';

/**
 * A generic fetch wrapper for interacting with the Daml JSON API.
 * @param endpoint The API endpoint to call (e.g., '/v1/query').
 * @param token The JWT token for authorization.
 * @param body The request body.
 * @returns The JSON response from the API.
 * @throws {LedgerServiceError} if the network request or API call fails.
 */
async function apiFetch<T>(endpoint: string, token: string, body: unknown): Promise<T> {
  try {
    const response = await fetch(`${JSON_API_URL}${endpoint}`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    });

    if (!response.ok) {
      const errorBody = await response.text();
      throw new Error(`API request failed with status ${response.status}: ${errorBody}`);
    }

    const jsonResponse = await response.json();
    if (jsonResponse.status !== 200) {
      throw new Error(`API returned non-200 status: ${JSON.stringify(jsonResponse.errors)}`);
    }

    return jsonResponse as T;

  } catch (error) {
    console.error(`Ledger API call to ${endpoint} failed:`, error);
    throw new LedgerServiceError(`Failed to communicate with the ledger: ${error instanceof Error ? error.message : String(error)}`);
  }
}

/**
 * Queries the ledger for active contracts of a specific template.
 * @param templateIds An array of template IDs to query for.
 * @param token The JWT token for authorization.
 * @param query An optional query payload to filter contracts.
 * @returns A promise that resolves to an array of active contracts.
 */
async function queryContracts<T>(templateIds: string[], token: string, query: Record<string, unknown> = {}): Promise<LedgerContract<T>[]> {
  const response = await apiFetch<{ result: LedgerContract<T>[] }>('/v1/query', token, { templateIds, query });
  return response.result;
}

/**
 * Fetches all active `Asset` contracts for which the given party is the custodian.
 *
 * @param party The party ID of the custodian.
 * @param token The JWT token for authorization.
 * @returns A promise that resolves to an array of `Asset` contracts.
 */
export async function getActiveAssetsByCustodian(party: string, token: string): Promise<LedgerContract<Asset>[]> {
  return queryContracts<Asset>([Main.Asset.Asset.templateId], token, { custodian: party });
}

/**
 * Fetches the complete history and current state of a specific asset by its ID.
 * This involves querying for the current asset state, all historical custody transfers,
 * and all checkpoints, then merging and sorting them into a chronological timeline.
 *
 * @param assetId The unique identifier of the asset.
 * @param token The JWT token for authorization.
 * @returns A promise that resolves to an `AssetProvenance` object.
 * @throws {LedgerServiceError} if the asset or its history cannot be found.
 */
export async function getAssetHistory(assetId: string, token: string): Promise<AssetProvenance> {
  const query = { assetId };

  // Fetch all related contracts in parallel
  const [currentAssets, transfers, checkpoints] = await Promise.all([
    queryContracts<Asset>([Main.Asset.Asset.templateId], token, query),
    queryContracts<CustodyTransfer>([Main.Custody.CustodyTransfer.templateId], token, query),
    queryContracts<Checkpoint>([Main.Checkpoint.Checkpoint.templateId], token, query),
  ]);

  if (currentAssets.length === 0) {
    throw new LedgerServiceError(`Asset with ID '${assetId}' not found.`);
  }
  if (currentAssets.length > 1) {
    console.warn(`Found multiple active assets with ID '${assetId}'. Using the first one.`);
  }
  const currentAsset = currentAssets[0];
  const manufacturer = currentAsset.payload.manufacturer;
  const description = currentAsset.payload.description;
  const creationTime = currentAsset.payload.creationTime;

  // We need to find the original `Asset` creation event to start the timeline
  // Assuming 'creationTime' is a field on the Asset template.
  const creationEvent: TimelineEvent = {
    type: 'creation',
    timestamp: creationTime,
    event: { assetId, manufacturer, custodian: manufacturer, description, creationTime } // Reconstructing the initial state
  };

  // Map raw contract data to TimelineEvent objects
  const transferEvents: TimelineEvent[] = transfers.map(t => ({
    type: 'transfer',
    timestamp: t.payload.timestamp,
    event: t.payload,
  }));

  const checkpointEvents: TimelineEvent[] = checkpoints.map(c => ({
    type: 'checkpoint',
    timestamp: c.payload.timestamp,
    event: c.payload,
  }));

  // Combine all events and sort chronologically
  const timeline = [creationEvent, ...transferEvents, ...checkpointEvents]
    .sort((a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime());

  return {
    currentAsset,
    timeline,
  };
}